[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = [ 'CtrlP', 'CtrlPBuffer', 'CtrlPClearCache' ]
hook_add = '''
let g:ctrlp_map = '<None>'
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_working_path_mode = 'r'
let g:ctrlp_custom_ignore = '.git\|node_modules'
let g:ctrlp_match_window = 'min:10'

nnoremap <Space>p :CtrlPClearCache<CR>:CtrlP<CR>
nnoremap <Space>b :CtrlPClearCache<CR>:CtrlPBuffer<CR>
'''

[[plugins]]
repo = "airblade/vim-gitgutter"
on_path = '.*'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js', 'json']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Space>a']
hook_add = '''
xmap <Space>a <Plug>(EasyAlign)
nmap <Space>a <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_map = ['<Space>gdiff', '<Space>blame', '<Space>glog']
hook_add = '''
nnoremap <Space>gdiff  :vertical Gdiff<CR>
nnoremap <Space>gblame :Gblame<CR>
nnoremap <Space>glog   :Glog<CR>
'''

